language: node_js

node_js:
- 'stable'

dist: trusty

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache:
  directories:
    - node_modules

before_install:
  - chmod +x build.sh

script: ./build.sh

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: './dist'
  fqdn: 'zastupovani.gytool.cz'
  on:
    branch: master