language: node_js

node_js:
- 'stable'

dist: trusty

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

before_install:
  - chmod +x build.sh

before_script:
  - npm run build

script: ./build.sh

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: './dist'
  fqdn: 'zastupovani.gytool.cz'
  verbose: true
  on:
    branch: master