language: node_js
node_js:
- 'stable'

script: ./build.sh

before_deploy:
- npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: './dist'
  fqdn: 'zastupovani.gytool.cz'
  on:
    branch: master