language: node_js

node_js:
- 'stable'

dist: trusty

before_script:
  - npm run build

script:
  - npm run cy:ci:prod:run
  - npm run test

cache:
  directories:
    - $HOME/.npm
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: './dist'
  fqdn: 'zastupovani.gytool.cz'
  verbose: true
  on:
    branch: master