language: node_js
node_js:
- 'stable'

script:
- npm run build && npm run test && npm run lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: './dist'
  on:
    branch: master