language: node_js

node_js:
- 'stable'

dist: trusty

install:
  - npm i -g npm@5.7.0
  - npm ci  

before_script:
  - npm run build

script:
  - npm run cy:ci:prod:run
  - npm run test

cache:
  directories:
    - $HOME/.npm

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: './dist'
  fqdn: 'zastupovani.gytool.cz'
  verbose: true
  on:
    branch: master